"""``lattice index`` — rebuild MANIFOLD.tsv, BLOOM.txt, GRAPH.tsv, MAP.md.

MANIFOLD.tsv: ngram → entry_ids reverse index
  - Scans entries/*.md for topics + claim text
  - Extracts 1- and 2-grams, maps each to matching entry IDs

BLOOM.txt: sorted unique token list
  - All unique tokens from all entries, sorted, one per line

GRAPH.tsv: entry_id → neighbor_ids from edges field
  - Reads edges: [...] from frontmatter

MAP.md: topic-level table of contents
  - Group entries by first topic, show count + most recent
"""
from __future__ import annotations

import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Optional, Set

from lattice.entry import Entry, iter_entries
from lattice.vault import discover_vault


def _extract_ngrams(text: str, max_n: int = 2) -> Set[str]:
    """Extract 1..max_n grams from text (lowercase, alphanumeric tokens only)."""
    tokens = re.findall(r"[\w가-힣]+", text.casefold())
    tokens = [t for t in tokens if len(t) > 1]
    ngrams: Set[str] = set()
    for i, tok in enumerate(tokens):
        ngrams.add(tok)
        if max_n >= 2 and i + 1 < len(tokens):
            ngrams.add(f"{tok} {tokens[i+1]}")
    return ngrams


def _entry_text_for_ngrams(e: Entry) -> str:
    """Combine topics + claim text for ngram extraction."""
    parts = list(e.topics)
    # First sentence/paragraph of body as claim text
    for line in e.body.strip().splitlines():
        s = line.strip()
        if s and not s.startswith("#"):
            parts.append(s)
            break
    return " ".join(parts)


def rebuild_index(vault_arg: Optional[str] = None) -> int:
    vault = discover_vault(vault_arg)
    if not vault.exists():
        print(f"error: vault does not exist: {vault}", file=sys.stderr)
        return 2

    entries_dir = vault / "entries"
    if not entries_dir.exists():
        print(f"error: {entries_dir} does not exist — run `lattice init` first", file=sys.stderr)
        return 2

    entries = iter_entries(vault, include_superseded=False)
    active = [e for e in entries if not e.deprecated]

    # Build MANIFOLD: ngram -> [entry_id, ...]
    manifold: Dict[str, List[str]] = defaultdict(list)
    all_tokens: Set[str] = set()

    for e in active:
        text = _entry_text_for_ngrams(e)
        ngrams = _extract_ngrams(text, max_n=2)
        for ng in ngrams:
            if e.id not in manifold[ng]:
                manifold[ng].append(e.id)
        # Also add raw tokens for BLOOM
        tokens = re.findall(r"[\w가-힣]+", e.raw.casefold())
        all_tokens.update(t for t in tokens if len(t) > 1)

    # Write MANIFOLD.tsv
    manifold_path = vault / "MANIFOLD.tsv"
    manifold_lines = ["# ngram\tentry_id1,entry_id2,..."]
    for ngram in sorted(manifold.keys()):
        ids_str = ",".join(manifold[ngram])
        manifold_lines.append(f"{ngram}\t{ids_str}")
    manifold_path.write_text("\n".join(manifold_lines) + "\n", encoding="utf-8")
    print(f"Wrote MANIFOLD.tsv ({len(manifold)} ngrams)")

    # Write BLOOM.txt
    bloom_path = vault / "BLOOM.txt"
    bloom_lines = sorted(all_tokens)
    bloom_path.write_text("\n".join(bloom_lines) + "\n", encoding="utf-8")
    print(f"Wrote BLOOM.txt ({len(bloom_lines)} tokens)")

    # Build GRAPH.tsv: entry_id -> neighbor_ids
    graph: Dict[str, List[str]] = {}
    for e in active:
        if e.edges:
            graph[e.id] = e.edges

    graph_path = vault / "GRAPH.tsv"
    graph_lines = ["# entry_id\tneighbor_id1,neighbor_id2,..."]
    for src in sorted(graph.keys()):
        neighbors_str = ",".join(graph[src])
        graph_lines.append(f"{src}\t{neighbors_str}")
    graph_path.write_text("\n".join(graph_lines) + "\n", encoding="utf-8")
    print(f"Wrote GRAPH.tsv ({len(graph)} nodes with edges)")

    # Build MAP.md: group by first topic
    topic_map: Dict[str, List[Entry]] = defaultdict(list)
    no_topic: List[Entry] = []
    for e in sorted(active, key=lambda x: (x.created or "", x.id), reverse=True):
        if e.topics:
            topic_map[e.topics[0]].append(e)
        else:
            no_topic.append(e)

    map_lines = [
        "# lattice MAP",
        "",
        "*Auto-generated by `lattice index`. Do not hand-edit.*",
        "",
        "Topic-level table of contents. For full entry list see MANIFOLD.tsv.",
        "",
    ]
    map_lines.append(f"**{len(active)} entries across {len(topic_map) + (1 if no_topic else 0)} topics.**")
    map_lines.append("")

    for topic in sorted(topic_map.keys()):
        topic_entries = topic_map[topic]
        map_lines.append(f"## {topic} ({len(topic_entries)} entries)")
        map_lines.append("")
        for e in topic_entries[:5]:
            summary = e.one_line_summary.replace("|", "\\|")
            map_lines.append(f"- `{e.id}` — {summary}")
        if len(topic_entries) > 5:
            map_lines.append(f"- *... and {len(topic_entries) - 5} more*")
        map_lines.append("")

    if no_topic:
        map_lines.append(f"## (untagged) ({len(no_topic)} entries)")
        map_lines.append("")
        for e in no_topic[:5]:
            summary = e.one_line_summary.replace("|", "\\|")
            map_lines.append(f"- `{e.id}` — {summary}")
        if len(no_topic) > 5:
            map_lines.append(f"- *... and {len(no_topic) - 5} more*")
        map_lines.append("")

    map_path = vault / "MAP.md"
    map_path.write_text("\n".join(map_lines) + "\n", encoding="utf-8")
    print(f"Wrote MAP.md ({len(topic_map)} topics)")

    print(f"\nIndex complete: {len(active)} entries indexed")
    return 0
