"""``lattice init [path]`` — initialize a lattice vault."""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Optional

from lattice import __version__
from lattice.vault import DEFAULT_VAULT, MARKER_FILE, set_active_vault

VAULT_SUBDIRS = ("entries", "sources", "superseded")


def _write_marker(vault: Path) -> None:
    marker = vault / MARKER_FILE
    marker.write_text(
        "# lattice vault marker\n"
        "version: 1\n"
        f"lattice-version: {__version__}\n",
        encoding="utf-8",
    )


def _write_initial_map(vault: Path) -> None:
    map_path = vault / "MAP.md"
    if map_path.exists():
        return
    map_path.write_text(
        "# lattice MAP\n\n"
        "*Topic-level table of contents. Auto-generated by `lattice index`.*\n\n"
        "---\n\n"
        "*0 entries. Add atomic claims to `entries/`, then run `lattice index`.*\n",
        encoding="utf-8",
    )


def init_vault(
    vault_arg: Optional[str] = None,
    activate: bool = True,
    refresh: bool = False,
) -> int:
    print("lattice — vault initialization")
    print("==============================")

    vault = Path(vault_arg).expanduser().resolve() if vault_arg else DEFAULT_VAULT.expanduser().resolve()

    if not vault.exists():
        vault.mkdir(parents=True, exist_ok=True)
        print(f"  created {vault}")
    else:
        print(f"  using existing {vault}")

    created_dirs = []
    for sub in VAULT_SUBDIRS:
        target = vault / sub
        if not target.exists():
            target.mkdir(parents=True, exist_ok=True)
            created_dirs.append(sub)
    if created_dirs:
        print(f"  Created subdirs: {', '.join(created_dirs)}")
    else:
        print("  Subdirs already in place")

    if not (vault / MARKER_FILE).exists() or refresh:
        _write_marker(vault)
        print(f"  Wrote {vault.name}/{MARKER_FILE}")
    else:
        print(f"  {MARKER_FILE} already exists (skipped)")

    _write_initial_map(vault)
    print(f"  Wrote {vault.name}/MAP.md")

    if activate:
        set_active_vault(vault)
        print(f"\n  Set {vault} as active vault")

    print("\nDone. Next steps:")
    print("  lattice status")
    print(f"  # Add entries to {vault.name}/entries/ with edges: [...] frontmatter")
    print("  # Then run: lattice index")
    return 0
