"""``akasha compile`` — prepare entry clusters for LLM narrative compilation.

akasha runs inside an LLM runtime (e.g. Claude Code). Compilation is done
by the LLM agent directly — not via external API calls.

This module handles:
1. Load all entries, group by primary topic (case-insensitive merge)
2. --dry-run: show topic list with entry counts
3. --dump <topic>: dump entries for one topic so LLM can write the doc
4. --write <topic> <file>: write a pre-composed narrative from stdin/arg
5. Pure-python aggregation fallback (structured concat, no LLM)

The LLM agent reads `akasha compile --dump <topic>`, writes compiled/{topic}.md.
"""
from __future__ import annotations

import sys
from collections import defaultdict
from datetime import date
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from akasha.entry import Entry, iter_entries
from akasha.vault import discover_vault


def _slugify(topic: str) -> str:
    """Convert topic string to a safe filename slug."""
    import re
    slug = topic.lower().strip()
    slug = re.sub(r"[^\w가-힣\-]+", "-", slug)
    slug = re.sub(r"-+", "-", slug)
    return slug.strip("-") or "general"


def _group_by_primary_topic(entries: List[Entry]) -> List[Tuple[str, List[Entry]]]:
    """Group entries by primary topic (case-insensitive merge). Returns [(topic, [entries])]."""
    # lowercase key → (canonical name, entries)
    topic_map: Dict[str, List[Entry]] = defaultdict(list)
    canonical: Dict[str, str] = {}  # lower → first-seen name (prefer lowercase)
    for e in entries:
        primary = e.topics[0] if e.topics else "general"
        key = primary.lower()
        # prefer lowercase canonical; only override if current is lower
        if key not in canonical or primary == primary.lower():
            canonical[key] = primary
        topic_map[key].append(e)
    return sorted(
        [(canonical[k], v) for k, v in topic_map.items()],
        key=lambda x: x[0].lower()
    )


def _compile_topic_llm(topic: str, entries: List[Entry], client) -> str:
    """Call Claude haiku to generate a narrative doc for the topic cluster."""
    # Collect entry texts (cap at 20 entries, ~4000 token budget)
    entry_texts = "\n\n---\n\n".join(
        f"[{e.id}] {e.raw}" for e in entries[:20]
    )

    prompt = f"""다음은 '{topic}' 주제에 관한 원자적 지식 entries입니다.
이를 하나의 coherent한 지식 문서로 통합해주세요.

요구사항:
- 300-600 단어
- 중복 제거, 논리적 흐름 구성
- 구체적 사실과 관계 보존 (일반화 금지)
- LLM이 검색 참조하기 좋은 형태 (인간 독자 아님)
- 한국어로 작성

Entries:
{entry_texts}

출력: 마크다운 형식의 지식 문서만 (frontmatter 없이)"""

    response = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=1000,
        messages=[{"role": "user", "content": prompt}],
    )
    return response.content[0].text


def _build_compiled_doc(
    topic: str, entries: List[Entry], narrative: str, today: str
) -> str:
    """Wrap narrative in YAML frontmatter."""
    entry_ids_str = ", ".join(e.id for e in entries[:20])
    if len(entries) > 20:
        entry_ids_str += f", ... ({len(entries) - 20} more)"
    return (
        "---\n"
        f"topic: {topic}\n"
        f"entry_count: {len(entries)}\n"
        f"entry_ids: [{entry_ids_str}]\n"
        f"generated: {today}\n"
        "---\n"
        "\n"
        f"# {topic}\n"
        "\n"
        f"{narrative}\n"
    )


def _write_compiled_index(
    vault: Path,
    topic_groups: List[Tuple[str, List[Entry]]],
    today: str,
) -> None:
    """Write COMPILED_INDEX.md — list of compiled docs with entry counts."""
    lines: List[str] = [
        "# akasha COMPILED_INDEX",
        "",
        f"*Auto-generated by `akasha compile` on {today}. Do not hand-edit.*",
        "",
        "| topic | entry_count | compiled_doc |",
        "|-------|-------------|--------------|",
    ]
    total = 0
    for topic, entries in topic_groups:
        slug = _slugify(topic)
        lines.append(f"| {topic} | {len(entries)} | `compiled/{slug}.md` |")
        total += len(entries)
    lines.append("")
    lines.append(f"*{len(topic_groups)} compiled docs, {total} total entries.*")

    out = vault / "COMPILED_INDEX.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  wrote COMPILED_INDEX.md ({len(topic_groups)} topics)")


def run_compile(
    vault_arg: Optional[str] = None,
    topic_filter: Optional[str] = None,
    dry_run: bool = False,
) -> int:
    """Compile topic clusters into narrative docs via Claude API."""
    vault = discover_vault(vault_arg)
    if not vault.exists():
        print(f"error: vault does not exist: {vault}", file=sys.stderr)
        return 2

    entries_dir = vault / "entries"
    if not entries_dir.exists():
        print(f"error: {entries_dir} does not exist — run `akasha init` first", file=sys.stderr)
        return 2

    all_entries = iter_entries(vault, include_superseded=False)
    active = [e for e in all_entries if not e.deprecated]

    if not active:
        print("No entries found. Add entries to entries/ then re-run.")
        return 0

    topic_groups = _group_by_primary_topic(active)

    if topic_filter:
        topic_groups = [(t, es) for t, es in topic_groups if t == topic_filter]
        if not topic_groups:
            print(f"No entries found for topic '{topic_filter}'.")
            return 0

    compiled_dir = vault / "compiled"
    compiled_dir.mkdir(exist_ok=True)
    today = str(date.today())

    if dry_run:
        print(f"akasha compile --dry-run: {len(topic_groups)} topics found")
        print()
        for topic, entries in topic_groups:
            slug = _slugify(topic)
            compiled_path = compiled_dir / f"{slug}.md"
            status = "✓" if compiled_path.exists() else "·"
            print(f"  {status} {topic:40s} {len(entries):3d} entries -> compiled/{slug}.md")
        print()
        compiled_count = sum(
            1 for t, _ in topic_groups
            if (compiled_dir / f"{_slugify(t)}.md").exists()
        )
        print(f"  {compiled_count}/{len(topic_groups)} compiled, "
              f"{len(topic_groups) - compiled_count} pending.")
        print()
        print("To compile: LLM reads entries and writes compiled/*.md directly.")
        print("  akasha compile --dump <topic>   # show entries for one topic")
        return 0

    # --dump mode: print entries for a topic so LLM can write the narrative
    if topic_filter:
        if not topic_groups:
            print(f"No entries for topic '{topic_filter}'.", file=sys.stderr)
            return 1
        topic, entries = topic_groups[0]
        slug = _slugify(topic)
        print(f"# Topic: {topic}  ({len(entries)} entries)")
        print(f"# Output: compiled/{slug}.md")
        print()
        for e in entries:
            print(f"## [{e.id}]")
            print(e.raw.strip())
            print()
        return 0

    # Default: pure-python structured aggregation (no LLM) as baseline
    compiled_groups: List[Tuple[str, List[Entry]]] = []
    for topic, entries in topic_groups:
        slug = _slugify(topic)
        out_path = compiled_dir / f"{slug}.md"
        if out_path.exists():
            compiled_groups.append((topic, entries))
            continue  # skip already compiled
        # Structured concat fallback
        body_parts = []
        for e in entries[:30]:
            body_parts.append(f"### {e.id}\n{e.raw.strip()}")
        narrative = "\n\n".join(body_parts)
        doc = _build_compiled_doc(topic, entries, narrative, today)
        out_path.write_text(doc, encoding="utf-8")
        compiled_groups.append((topic, entries))
        print(f"  aggregated: {topic} ({len(entries)} entries)")

    _write_compiled_index(vault, compiled_groups, today)
    total = sum(len(es) for _, es in compiled_groups)
    print(f"\nAggregated {len(compiled_groups)} topics, {total} entries.")
    print(f"Compiled docs: {compiled_dir}")
    print()
    print("Note: These are structured aggregations, not LLM narratives.")
    print("For LLM narrative quality: akasha compile --dump <topic>")
    print("then write compiled/{topic}.md from the output.")
    return 0
