"""``akasha index`` — rebuild INDEX.md, COMPILED_INDEX.md, and GRAPH.tsv.

INDEX.md: full entry catalog (id, type, topics, summary)
GRAPH.tsv: adjacency list from entry edges
COMPILED_INDEX.md: topic-level table of compiled docs (if compiled/ exists)
"""
from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Optional

from akasha.entry import Entry, iter_entries
from akasha.graph import build_graph, write_graph, count_graph_edges
from akasha.vault import discover_vault


INDEX_HEADER = """\
# akasha INDEX

*Auto-generated by `akasha index`. Do not hand-edit.*

Full entry catalog — use as session entry point.
Format: id | type | primary_topic | summary

"""


def rebuild_index(vault_arg: Optional[str] = None) -> int:
    """Rebuild INDEX.md and GRAPH.tsv."""
    vault = discover_vault(vault_arg)
    if not vault.exists():
        print(f"error: vault does not exist: {vault}", file=sys.stderr)
        return 2

    entries_dir = vault / "entries"
    if not entries_dir.exists():
        print(f"error: {entries_dir} does not exist — run `akasha init` first", file=sys.stderr)
        return 2

    all_entries = iter_entries(vault, include_superseded=False)
    active = [e for e in all_entries if not e.deprecated]
    active.sort(key=lambda e: (e.created or "", e.id), reverse=True)

    # Build and write GRAPH.tsv
    graph = build_graph(active)
    write_graph(vault, graph)
    print(f"Wrote GRAPH.tsv ({len(graph)} nodes with edges)")

    # Build INDEX.md
    index_lines = [INDEX_HEADER]
    index_lines.append("| id | type | primary_topic | summary |")
    index_lines.append("|----|------|---------------|---------|")
    for e in active:
        primary = e.topics[0] if e.topics else ""
        summary = e.one_line_summary.replace("|", "\\|").replace("\n", " ")[:80]
        index_lines.append(f"| `{e.id}` | {e.type} | {primary} | {summary} |")
    index_lines.append("")
    index_lines.append(f"*{len(active)} total entries.*")

    index_path = vault / "INDEX.md"
    index_path.write_text("\n".join(index_lines) + "\n", encoding="utf-8")
    print(f"Wrote INDEX.md ({len(active)} entries)")

    # Rebuild COMPILED_INDEX.md if compiled/ exists
    compiled_dir = vault / "compiled"
    if compiled_dir.exists():
        _rebuild_compiled_index(vault, active, compiled_dir)

    print(f"\nIndex complete: {len(active)} entries, {len(graph)} graph nodes")
    return 0


def _rebuild_compiled_index(vault: Path, entries: List[Entry], compiled_dir: Path) -> None:
    """Rebuild COMPILED_INDEX.md from existing compiled/ files."""
    from datetime import date

    # Build topic -> entry count map
    topic_counts: Dict[str, int] = defaultdict(int)
    for e in entries:
        primary = e.topics[0] if e.topics else "general"
        topic_counts[primary] += 1

    compiled_files = sorted(compiled_dir.glob("*.md"))
    if not compiled_files:
        return

    today = str(date.today())
    lines: List[str] = [
        "# akasha COMPILED_INDEX",
        "",
        f"*Auto-generated by `akasha index` on {today}. Do not hand-edit.*",
        "",
        "| compiled_doc | entry_count |",
        "|--------------|-------------|",
    ]
    for f in compiled_files:
        slug = f.stem
        count = topic_counts.get(slug, "?")
        lines.append(f"| `compiled/{f.name}` | {count} |")
    lines.append("")
    lines.append(f"*{len(compiled_files)} compiled docs.*")

    out = vault / "COMPILED_INDEX.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote COMPILED_INDEX.md ({len(compiled_files)} docs)")
