"""``facet compile`` — shard entries → narrative compiled docs.

Pure Python text aggregation. No LLM API calls.

Algorithm:
1. Load all entries, group by shard (using physical shards/ directory structure)
2. For each shard:
   a. Group entries by primary topic
   b. Concatenate entry bodies per topic cluster
   c. Write compiled/{shard}.md with narrative structure
3. Write COMPILED_INDEX.md with summary table

The compiled docs are intentionally verbose so TF-IDF search has more text
surface area to match against — this tests the hypothesis that longer
narrative context improves recall over atomic entry search.
"""
from __future__ import annotations

import sys
from collections import defaultdict
from datetime import date
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from facet.entry import Entry, iter_shard_entries
from facet.vault import discover_vault, iter_shards


def _cluster_by_topic(entries: List[Entry]) -> List[Tuple[str, List[Entry]]]:
    """Group entries by primary topic. Returns [(topic, [entries])] sorted by topic."""
    topic_map: Dict[str, List[Entry]] = defaultdict(list)
    for e in entries:
        primary = e.topics[0] if e.topics else "general"
        topic_map[primary].append(e)
    return sorted(topic_map.items())


def _compile_shard(shard_name: str, entries: List[Entry], today: str) -> str:
    """Compile a list of entries into a single narrative markdown document."""
    entry_ids = [e.id for e in entries]
    all_topics = sorted({t for e in entries for t in e.topics})
    clusters = _cluster_by_topic(entries)

    lines: List[str] = []

    # --- Frontmatter ---
    lines.append("---")
    ids_joined = ", ".join(entry_ids[:20])
    if len(entry_ids) > 20:
        ids_joined += f", ... ({len(entry_ids) - 20} more)"
    lines.append(f"compiled_from: [{ids_joined}]")
    lines.append(f"shard: {shard_name}")
    topics_joined = ", ".join(all_topics[:15])
    if len(all_topics) > 15:
        topics_joined += f", ... ({len(all_topics) - 15} more)"
    lines.append(f"topics: [{topics_joined}]")
    lines.append(f"generated: {today}")
    lines.append(f"entry_count: {len(entries)}")
    lines.append("---")
    lines.append("")

    # --- Title ---
    lines.append(f"# {shard_name} — Knowledge Overview")
    lines.append("")
    lines.append(
        f"*Auto-compiled from {len(entries)} entries. Do not hand-edit — "
        "regenerate with `facet compile`.*"
    )
    lines.append("")

    # --- Topic clusters (narrative body) ---
    for topic, topic_entries in clusters:
        if not topic_entries:
            continue
        lines.append(f"## {topic}")
        lines.append("")
        for e in topic_entries:
            body_stripped = e.body.strip()
            if body_stripped:
                lines.append(body_stripped)
                lines.append("")
        # Add edge mentions for entries in this cluster that have edges
        edge_lines: List[str] = []
        for e in topic_entries:
            for edge in e.edges:
                to = edge.get("to", "")
                etype = edge.get("type", "")
                if to and etype:
                    edge_lines.append(f"  - `{e.id}` {etype} `{to}`")
        if edge_lines:
            lines.append("*Relationships:*")
            lines.extend(edge_lines)
            lines.append("")

    # --- Entry Index ---
    lines.append("## Entry Index")
    lines.append("")
    for e in sorted(entries, key=lambda x: (x.created or "", x.id)):
        summary = e.one_line_summary[:100]
        lines.append(f"- `{e.id}` ({e.type or 'entry'}, {e.confidence or '?'}) — {summary}")
    lines.append("")

    # --- Sources ---
    sources = sorted({e.source for e in entries if e.source})
    if sources:
        lines.append("## Sources")
        lines.append("")
        for src in sources:
            citing_ids = [e.id for e in entries if e.source == src]
            lines.append(f"- `{src}`: {', '.join(f'`{i}`' for i in citing_ids[:5])}")
        lines.append("")

    return "\n".join(lines)


def _write_compiled_index(vault: Path, counts: Dict[str, int], today: str) -> None:
    """Write COMPILED_INDEX.md — list of compiled docs with entry counts."""
    lines: List[str] = [
        "# facet COMPILED_INDEX",
        "",
        f"*Auto-generated by `facet compile` on {today}. Do not hand-edit.*",
        "",
        "| shard | entry_count | compiled_doc |",
        "|-------|-------------|--------------|",
    ]
    total = 0
    for shard_name in sorted(counts.keys()):
        count = counts[shard_name]
        total += count
        lines.append(f"| {shard_name} | {count} | `compiled/{shard_name}.md` |")
    lines.append("")
    lines.append(f"*{len(counts)} compiled docs, {total} total entries.*")

    out = vault / "COMPILED_INDEX.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  wrote COMPILED_INDEX.md ({len(counts)} docs)")


def run_compile(vault_arg: Optional[str] = None, shard_filter: Optional[str] = None) -> int:
    """Compile all shards (or one shard): shards/ → compiled/."""
    vault = discover_vault(vault_arg)
    if not vault.exists():
        print(f"error: vault does not exist: {vault}", file=sys.stderr)
        return 2

    shards_dir = vault / "shards"
    if not shards_dir.exists():
        print(f"error: {shards_dir} does not exist — run `facet init` first", file=sys.stderr)
        return 2

    compiled_dir = vault / "compiled"
    compiled_dir.mkdir(exist_ok=True)

    today = str(date.today())

    # Build {shard_name: [entries]} from physical shard directories
    by_shard: Dict[str, List[Entry]] = {}
    for shard_name, shard_path in iter_shards(vault):
        if shard_filter and shard_name != shard_filter:
            continue
        entries = iter_shard_entries(shard_path, shard_name)
        active = [e for e in entries if not e.deprecated]
        if active:
            by_shard[shard_name] = active

    if not by_shard:
        if shard_filter:
            print(f"No entries found in shard '{shard_filter}'.")
        else:
            print("No entries found. Add entries to shards/ then re-run.")
        return 0

    compiled_counts: Dict[str, int] = {}
    for shard_name in sorted(by_shard.keys()):
        entries = by_shard[shard_name]
        doc = _compile_shard(shard_name, entries, today)
        out_path = compiled_dir / f"{shard_name}.md"
        out_path.write_text(doc, encoding="utf-8")
        compiled_counts[shard_name] = len(entries)
        print(f"  compiled shard '{shard_name}': {len(entries)} entries -> {out_path.name}")

    # Write COMPILED_INDEX.md (only when compiling all shards)
    if not shard_filter:
        _write_compiled_index(vault, compiled_counts, today)

    total_compiled = sum(compiled_counts.values())
    print(f"\nCompiled {len(compiled_counts)} shards, {total_compiled} entries total.")
    print(f"Compiled docs: {compiled_dir}")
    return 0
