"""``facet index`` — rebuild MANIFEST.md and all shard _index.md files.

For each shard in shards/:
  - Scans *.md entries (skip _index.md)
  - Writes shard/_index.md: | id | type | topics | summary |

Then writes top-level MANIFEST.md: shard name, entry count, topics.
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Optional

from facet.entry import Entry, iter_shard_entries
from facet.vault import discover_vault, iter_shards


SHARD_INDEX_HEADER = """\
# {shard} — shard index

*Auto-generated by `facet index`. Do not hand-edit.*

| id | type | topics | summary | confidence |
|----|------|--------|---------|------------|
"""

MANIFEST_HEADER = """\
# facet MANIFEST

*Auto-generated by `facet index`. Do not hand-edit.*

Top-level table of contents across all shards.

"""

INDEX_HEADER = """\
# facet INDEX

*Auto-generated by `facet index`. Do not hand-edit.*

Full entry catalog — use this as the session entry point.
Format: `id | shard | type | topics | summary`

"""


def _format_entry_row(e: Entry) -> str:
    topics = ", ".join(e.topics) if e.topics else ""
    summary = e.one_line_summary.replace("|", "\\|").replace("\n", " ")
    return f"| `{e.id}` | {e.type} | {topics} | {summary} | {e.confidence} |"


def _rebuild_shard_index(shard_name: str, shard_path: Path) -> int:
    """Rebuild _index.md for a single shard. Returns entry count."""
    entries = iter_shard_entries(shard_path, shard_name)
    active = [e for e in entries if not e.deprecated]
    active.sort(key=lambda e: (e.created or "", e.id), reverse=True)

    lines = [SHARD_INDEX_HEADER.format(shard=shard_name)]
    for e in active:
        lines.append(_format_entry_row(e))
    lines.append("")
    lines.append(f"*{len(active)} active entries.*")

    index_path = shard_path / "_index.md"
    index_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(active)


def rebuild_index(vault_arg: Optional[str] = None) -> int:
    """Rebuild _index.md for all shards and MANIFEST.md."""
    vault = discover_vault(vault_arg)
    if not vault.exists():
        print(f"error: vault does not exist: {vault}", file=sys.stderr)
        return 2

    shards_dir = vault / "shards"
    if not shards_dir.exists():
        print(f"error: {shards_dir} does not exist — run `facet init` first", file=sys.stderr)
        return 2

    shard_counts: dict = {}
    for shard_name, shard_path in iter_shards(vault):
        count = _rebuild_shard_index(shard_name, shard_path)
        shard_counts[shard_name] = count
        print(f"  rebuilt shard '{shard_name}': {count} entries")

    # Build MANIFEST.md
    manifest_lines = [MANIFEST_HEADER]
    manifest_lines.append("| shard | entries | path |")
    manifest_lines.append("|-------|---------|------|")
    total = 0
    for shard_name in sorted(shard_counts):
        count = shard_counts[shard_name]
        total += count
        manifest_lines.append(f"| {shard_name} | {count} | `shards/{shard_name}/` |")
    manifest_lines.append("")
    manifest_lines.append(f"*{len(shard_counts)} shards, {total} total entries.*")

    manifest_path = vault / "MANIFEST.md"
    manifest_path.write_text("\n".join(manifest_lines) + "\n", encoding="utf-8")

    # Build INDEX.md — full entry catalog (cairn-style session entry point)
    all_entries: list = []
    for shard_name, shard_path in iter_shards(vault):
        for e in iter_shard_entries(shard_path, shard_name):
            if not e.deprecated:
                all_entries.append(e)
    all_entries.sort(key=lambda e: (e.created or "", e.id), reverse=True)

    index_lines = [INDEX_HEADER]
    index_lines.append("| id | shard | type | topics | summary |")
    index_lines.append("|----|-------|------|--------|---------|")
    for e in all_entries:
        topics = ", ".join(e.topics[:3]) if e.topics else ""
        summary = e.one_line_summary.replace("|", "\\|").replace("\n", " ")[:80]
        index_lines.append(f"| `{e.id}` | {e.shard} | {e.type} | {topics} | {summary} |")
    index_lines.append("")
    index_lines.append(f"*{len(all_entries)} total entries across {len(shard_counts)} shards.*")

    index_path = vault / "INDEX.md"
    index_path.write_text("\n".join(index_lines) + "\n", encoding="utf-8")

    print(f"\nRebuilt {manifest_path}")
    print(f"  shards: {len(shard_counts)}")
    print(f"  total entries: {total}")
    print(f"Rebuilt {index_path} ({len(all_entries)} entries)")
    return 0
