"""``facet init [path]`` — initialize a facet vault."""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Optional

from facet import __version__
from facet.vault import DEFAULT_VAULT, MARKER_FILE, set_active_vault

VAULT_SUBDIRS = ("shards", "sources", "superseded")


def _write_marker(vault: Path) -> None:
    marker = vault / MARKER_FILE
    marker.write_text(
        "# facet vault marker\n"
        "version: 1\n"
        f"facet-version: {__version__}\n",
        encoding="utf-8",
    )


def _write_initial_manifest(vault: Path) -> None:
    manifest_path = vault / "MANIFEST.md"
    if manifest_path.exists():
        return
    manifest_path.write_text(
        "# facet MANIFEST\n\n"
        "*Top-level table of contents. Auto-generated by `facet index`.*\n\n"
        "---\n\n"
        "| shard | entries | path |\n"
        "|-------|---------|------|\n\n"
        "*0 shards. Create subdirectories under `shards/` then run `facet index`.*\n",
        encoding="utf-8",
    )


def _write_example_aliases(vault: Path) -> None:
    aliases_path = vault / "ALIASES.tsv"
    if aliases_path.exists():
        return
    aliases_path.write_text(
        "# ALIASES.tsv — map surface forms to canonical shard names\n"
        "# Format: surface_form<TAB>shard_name\n"
        "# Example:\n"
        "#   orbit r4\torbit\n"
        "#   dispatch score\torbit\n",
        encoding="utf-8",
    )


def init_vault(
    vault_arg: Optional[str] = None,
    activate: bool = True,
    refresh: bool = False,
) -> int:
    print("facet — vault initialization")
    print("============================")

    vault = Path(vault_arg).expanduser().resolve() if vault_arg else DEFAULT_VAULT.expanduser().resolve()

    if not vault.exists():
        vault.mkdir(parents=True, exist_ok=True)
        print(f"  created {vault}")
    else:
        print(f"  using existing {vault}")

    created_dirs = []
    for sub in VAULT_SUBDIRS:
        target = vault / sub
        if not target.exists():
            target.mkdir(parents=True, exist_ok=True)
            created_dirs.append(sub)
    if created_dirs:
        print(f"  Created subdirs: {', '.join(created_dirs)}")
    else:
        print("  Subdirs already in place")

    if not (vault / MARKER_FILE).exists() or refresh:
        _write_marker(vault)
        print(f"  Wrote {vault.name}/{MARKER_FILE}")
    else:
        print(f"  {MARKER_FILE} already exists (skipped)")

    _write_initial_manifest(vault)
    print(f"  Wrote {vault.name}/MANIFEST.md")

    _write_example_aliases(vault)
    print(f"  Wrote {vault.name}/ALIASES.tsv")

    if activate:
        set_active_vault(vault)
        print(f"\n  Set {vault} as active vault")

    print("\nDone. Next steps:")
    print("  facet status")
    print(f"  # Create shard directories under {vault.name}/shards/<shard-name>/")
    print("  # Add ALIASES.tsv entries to map surface forms to shards")
    print("  # Then run: facet index")
    return 0
