"""``cairn index`` — rebuild INDEX.md from vault/entries/.

INDEX.md is the LLM's table of contents. It's the first file every session
reads. This command scans entries/ and regenerates the index as a single
append-only markdown table.

Format:

    | id | type | topics | summary | confidence | last_retrieved |

Rebuild (not append) is chosen for v0 simplicity: the full scan is cheap
for thousands of entries. Future versions can switch to incremental append
for very large vaults.
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Optional

from cairn.entry import Entry, iter_entries
from cairn.vault import discover_vault


INDEX_HEADER = """# cairn INDEX

*The brain's table of contents. Read this first every session.*

This file is auto-generated by `cairn index`. Do not hand-edit — changes
will be overwritten on next rebuild. To add or update an entry, write or
supersede the underlying file in `entries/`.

Format: `id | type | topics | summary | confidence | last_retrieved`

---
"""


def format_entry_row(e: Entry) -> str:
    topics = ", ".join(e.topics) if e.topics else ""
    summary = e.one_line_summary.replace("|", "\\|").replace("\n", " ")
    # pipe in summary needs escaping for markdown table
    return f"| `{e.id}` | {e.type} | {topics} | {summary} | {e.confidence} | {e.last_retrieved} |"


def rebuild_index(vault_arg: Optional[str] = None) -> int:
    """Scan vault/entries/ and rewrite vault/INDEX.md."""
    vault = discover_vault(vault_arg)
    if not vault.exists():
        print(f"error: vault does not exist: {vault}", file=sys.stderr)
        return 2

    entries_dir = vault / "entries"
    if not entries_dir.exists():
        print(f"error: {entries_dir} does not exist — run `cairn init` first", file=sys.stderr)
        return 2

    entries = iter_entries(vault, include_superseded=False)

    lines = [INDEX_HEADER]
    lines.append("| id | type | topics | summary | confidence | last_retrieved |")
    lines.append("|----|------|--------|---------|------------|----------------|")
    # Sort by created date desc, then id asc
    for e in sorted(entries, key=lambda x: (x.created or "", x.id), reverse=True):
        if e.deprecated:
            continue
        lines.append(format_entry_row(e))

    lines.append("")
    lines.append(f"*{len([e for e in entries if not e.deprecated])} active entries. Deprecated entries hidden; see `superseded/` for history.*")

    index_path = vault / "INDEX.md"
    index_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Rebuilt {index_path}")
    print(f"  entries:     {len(entries)}")
    print(f"  active rows: {len([e for e in entries if not e.deprecated])}")
    return 0
