"""``cairn init [path]`` — initialize a cairn vault."""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Optional

from cairn import __version__
from cairn.vault import DEFAULT_VAULT, MARKER_FILE, set_active_vault

VAULT_SUBDIRS = ("entries", "sources", "superseded")


def _write_marker(vault: Path) -> None:
    marker = vault / MARKER_FILE
    marker.write_text(
        "# cairn vault marker\n"
        "version: 1\n"
        f"cairn-version: {__version__}\n",
        encoding="utf-8",
    )


def _write_initial_index(vault: Path) -> None:
    index_path = vault / "INDEX.md"
    if index_path.exists():
        return
    index_path.write_text(
        "# cairn INDEX\n\n"
        "*The brain's table of contents. Read this first every session.*\n\n"
        "This file is auto-generated by `cairn index`. Run it after adding "
        "new entries.\n\n"
        "---\n\n"
        "| id | type | topics | summary | confidence | last_retrieved |\n"
        "|----|------|--------|---------|------------|----------------|\n\n"
        "*0 active entries. Drop sources into `sources/`, then author atomic "
        "claims in `entries/`.*\n",
        encoding="utf-8",
    )


def _write_readme(vault: Path) -> None:
    """Write a minimal README.md that the user (not the LLM) reads."""
    readme = vault / "README.md"
    if readme.exists():
        return
    readme.write_text(
        "# cairn vault — user guide\n\n"
        "This is a **cairn-vault**. It's a knowledge base designed for an LLM\n"
        "to read and maintain, with you (the human) as source provider and\n"
        "occasional auditor.\n\n"
        "## Your 3 verbs\n\n"
        "1. **drop** — place raw source files into `sources/`. The LLM will\n"
        "   ingest them on the next session.\n"
        "2. **ask** — start an LLM session and ask questions. The LLM handles\n"
        "   search and retrieval through the vault.\n"
        "3. **audit** — open any file in `entries/` to spot-check what the\n"
        "   LLM has written. Every entry is plain markdown with a source link.\n\n"
        "## What NOT to do\n\n"
        "- **Don't hand-edit `INDEX.md`.** It's auto-generated. Edit the underlying\n"
        "  entries instead (or let the LLM supersede them).\n"
        "- **Don't reorganize directories.** The flat `entries/` is load-bearing.\n"
        "- **Don't delete entries.** Use `deprecated: true` in frontmatter; the\n"
        "  LLM will handle archival to `superseded/`.\n"
        "- **Don't write entries yourself.** The format (YAML frontmatter +\n"
        "  atomic 400-token cap) is tuned for LLM consumption, not human\n"
        "  authoring. Drop sources, let the LLM produce entries.\n\n"
        "## Directory layout\n\n"
        "```\n"
        ".cairn-vault    # marker\n"
        "INDEX.md        # LLM's table of contents (auto-generated)\n"
        "README.md       # this file\n"
        "entries/        # atomic claim files (one claim per file, ~400 tokens)\n"
        "sources/        # raw imports you drop for the LLM to ingest\n"
        "superseded/     # archived old entries (never deleted)\n"
        "```\n\n"
        "## CLI quick reference\n\n"
        "```\n"
        "cairn status                # vault state + counts\n"
        "cairn search \"<query>\"      # lexical search over entries\n"
        "cairn index                 # rebuild INDEX.md (after adding entries)\n"
        "```\n\n"
        "## Philosophy\n\n"
        "cairn is named after the stone piles hikers build along trails — each\n"
        "traveler adds a small stone, and over time the cairn marks the way.\n"
        "Each atomic entry is a stone. The cairn accumulates. No single stone\n"
        "is the whole monument, but together they form a trail.\n\n"
        "For the full design, see:\n"
        "`~/_/projects/cairn/docs/design-v0.md` (project repo)\n",
        encoding="utf-8",
    )


def init_vault(
    vault_arg: Optional[str] = None,
    activate: bool = True,
    refresh: bool = False,
) -> int:
    """Initialize a cairn vault."""
    print("cairn — vault initialization")
    print("============================")

    vault = Path(vault_arg).expanduser().resolve() if vault_arg else DEFAULT_VAULT.expanduser().resolve()

    if not vault.exists():
        vault.mkdir(parents=True, exist_ok=True)
        print(f"  ↳ created {vault}")
    else:
        print(f"  ↳ using existing {vault}")

    # Subdirs
    created_dirs = []
    for sub in VAULT_SUBDIRS:
        target = vault / sub
        if not target.exists():
            target.mkdir(parents=True, exist_ok=True)
            created_dirs.append(sub)
    if created_dirs:
        print(f"  Created subdirs: {', '.join(created_dirs)}")
    else:
        print("  Subdirs already in place ✓")

    # Marker
    if not (vault / MARKER_FILE).exists() or refresh:
        _write_marker(vault)
        print(f"  Wrote {vault.name}/{MARKER_FILE} ✓")
    else:
        print(f"  {MARKER_FILE} already exists (skipped)")

    # README
    _write_readme(vault)
    print(f"  Wrote {vault.name}/README.md ✓")

    # Initial INDEX.md
    _write_initial_index(vault)
    print(f"  Wrote {vault.name}/INDEX.md ✓ (empty table)")

    # Activate
    if activate:
        set_active_vault(vault)
        print(f"\n  Set {vault} as active vault ✓")

    print("\nDone. Next steps:")
    print(f"  cairn status")
    print(f"  # Then drop sources into {vault.name}/sources/")
    print(f"  # The LLM will produce entries from them.")
    return 0
